### PR TITLE
Python3 compatibility

### LINKED ISSUE #57: Hypy: Python 3 Compatibility
Hypy currently only supports Python2, which is no longer maintained after the end of the year. Many packages are also dropping Python2 support (see https://python3statement.org/ ), or have already done so, so it is difficult to write code which combines Hypy and other packages.

Therefore it would be great to make Hypy compatible with Python3. As it's possible to make code compatible with both Python2 and Python3 (see https://python-future.org/ ), that would probably be the best way to go.

### PR DESCRIPTION
**Pull request by MaxGaukler**
After a one day of work I now claim that hypy works with python3 (and still with python2). There are still some gaps on which I'd be happy about collaboration:
- Not all relevant code paths are yet covered by tests. Therefore there may be hidden bugs.
- strategy.py in hypy was broken since 2016, I removed it.
- the hyst python bridge and its python detection uses python2 and I'm not sure how to test it
- There is a slight difference between python2 and python3 (maybe due to rounding) in pysim.simulate_der_range. For example, test_simulate_der_range in test_pysim_utils has output "0.0,4.0;2.0,6.0" in python2 and "0.0,4.0;2.0,5.999999999999957" in python3
- Similar but slightly more pronounced, there are numerical differences in doc/transformation_passes/hybridization/out_vanderpol_hybridized_plot.xml. However, the difference from what's stored in the git repository compared to what is computed by python2 (before my changes) is much larger than the difference between python2 and python3. This means that if there is a problem, it is not new.
- Some "end-user" testing may be required - I haven't actually tested hypy for "real-world" use-cases.

This fixes #57.

### CODE REVIEW

**Comment by MaxGaukler** [comment]
As far as I tested, hypy works fine under python3, so this pull request should be ready to merge.

**Comment by ttj** [comment]
Thanks for fixing the other one Max, this one now has some new conflicts, could you please check and fix?

**Comment by MaxGaukler** [comment]
Thanks, I'm working on it. Could you please have a look at #52?

**Comment by ttj** [comment]
Ok, thanks, I think I've enabled it:

https://travis-ci.com/github/verivital/hyst/builds/154621891

Please let me know if I can merge this one or if there are still changes needed.

**Comment by ttj** [comment]
thanks!

**Pull request merged**
